export const categories = {
  environment: [
    "صنعتی",
    "نما",
    "استخر-حمام",
    "پارکینگ- محیط خارجی",
    "مسکونی",
    "تجاری و پرتردد",
    "دکوراتیو",
  ],
  style: [
    "MARBLE",
    "STONE",
    "WOOD",
    "ABSTRACT",
    "CEMENT",
    "SWIMMING POOL",
    "HEAVY DUTY",
    "TERRAZZO",
    "MONOCOLOR",
    "FABRIC",
  ],
  color: [
    "سفید",
    "مشکی",
    "خاکستری",
    "بژ",
    "زرد",
    "قرمز",
    "نارنجی",
    "چند رنگ",
    "سبز",
    "قهوه ای",
    "صورتی",
    "آبی",
  ],
  size: [
    "100x100",
    "60x120",
    "60x60",
    "40x40",
    "33x33",
    "30x30",
    "25x25",
    "20x20",
    "15x15",
    "11.5x24",
    "7x29",
    "20x120",
  ],
  industri: ["ضد اسید", "ضد قلیا", "ضد لغزش", "صنعتی", "قطعات تکمیلی"],

  thicknesses: [
    "8mm",
    "9mm",
    "10mm",
    "11mm",
    "12mm",
    "13mm",
    "14mm",
    "15mm",
    "20mm",
  ],
};

export const products = [
  {
    id: 1,
    title: "arses",
    image: "/images/envairment/1.jpg",
    description: "کاناپه‌ای مدرن و راحت با رنگ سفید مناسب اتاق نشیمن داخلی.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["سفید", "بژ"],
    size: ["60*60", "40*40"],
    isSave: false,
    industry: [],
    thickness: "20mm",
  },
  {
    id: 2,
    title: "serenity",
    image: "/images/envairment/2.jpg",
    description:
      "چراغی زیبا به سبک روستیک با رنگ طلایی و سایز خیلی بزرگ برای بالکن خارجی.",
    environment: ["پارکینگ- محیط خارجی", "تجاری و پرتردد"],
    style: ["WOOD", "HEAVY DUTY"],
    color: ["زرد", "نارنجی"],
    size: ["100*100", "60*120"],
    isSave: true,
    industry: ["ضد لغزش"],
    thickness: "13mm",
  },
  {
    id: 3,
    title: "terrazo",
    image: "/images/envairment/3.jpg",
    description:
      "میز کاری مینیمال با رنگ مشکی و اندازه متوسط مناسب فضای دفتر کار.",
    environment: ["تجاری و پرتردد"],
    style: ["WOOD", "MONOCOLOR"],
    color: ["مشکی", "خاکستری"],
    size: ["60*60", "33*33"],
    isSave: false,
    industry: [],
    thickness: "13mm",
  },
  {
    id: 4,
    title: "titan",
    image: "/images/envairment/4.jpg",
    description: "کابینت آشپزخانه به سبک کلاسیک با رنگ سفید و سایز بزرگ.",
    environment: ["مسکونی"],
    style: ["WOOD", "MARBLE"],
    color: ["سفید"],
    size: ["60*120", "40*40"],
    isSave: false,
    industry: [],
    thickness: "12mm",
  },
  {
    id: 5,
    title: "travertino",
    image: "/images/envairment/5.jpg",
    description:
      "صندلی به رنگ قرمز با طراحی صنعتی، مناسب برای انبار و سالن تولید.",
    environment: ["صنعتی"],
    style: ["HEAVY DUTY"],
    color: ["قرمز", "مشکی"],
    size: ["30*30", "25*25"],
    isSave: true,
    industry: ["صنعتی", "ضد اسید"],
    thickness: "14mm",
  },
  {
    id: 6,
    title: "arses",
    image: "/images/envairment/6.jpg",
    description: "کرسى مدرن به رنگ آبی مناسب اتاق نشیمن داخلی.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["آبی", "سبز"],
    size: ["20*20", "15*15"],
    isSave: true,
    industry: [],
    thickness: "12mm",
  },
  {
    id: 7,
    title: "palette",
    image: "/images/envairment/7.jpg",
    description: "پرده‌های کلاسیک به رنگ سبز مناسب اتاق خواب و نشیمن.",
    environment: ["مسکونی"],
    style: ["FABRIC"],
    color: ["سبز", "بژ"],
    size: ["60*60", "40*40"],
    isSave: false,
    industry: [],
    thickness: "8mm",
  },
  {
    id: 8,
    title: "palette2",
    image: "/images/envairment/8.jpg",
    description: "شلف مینیمال سفید رنگ مناسب آشپزخانه و دفتر کار.",
    environment: ["صنعتی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["سفید", "بژ"],
    size: ["60*120", "40*40"],
    isSave: false,
    industry: ["ضد لغزش"],
    thickness: "8mm",
  },
  {
    id: 9,
    title: "palette3",
    image: "/images/envairment/9.jpg",
    description: "میز چوبی روستیک مناسب سالن تولید و فضای باز.",
    environment: ["صنعتی", "نما"],
    style: ["WOOD", "HEAVY DUTY"],
    color: ["قهوه ای", "زرد"],
    size: ["100*100", "60*60"],
    isSave: false,
    industry: ["صنعتی"],
    thickness: "9mm",
  },
  {
    id: 10,
    title: "palette4",
    image: "/images/envairment/10.jpg",
    description: "شلف فلزی صنعتی مناسب انبار و کارخانه.",
    environment: ["صنعتی", "تجاری و پرتردد"],
    style: ["HEAVY DUTY"],
    color: ["خاکستری", "مشکی"],
    size: ["60*60", "33*33"],
    isSave: true,
    industry: ["صنعتی", "ضد اسید"],
    thickness: "9mm",
  },
  {
    id: 11,
    title: "palette5",
    image: "/images/envairment/11.jpg",
    description: "چراغ ایستاده مدرن به رنگ مشکی مناسب سالن پذیرایی.",
    environment: ["دکوراتیو", "مسکونی"],
    style: ["MONOCOLOR", "FABRIC"],
    color: ["مشکی", "سفید"],
    size: ["40*40", "25*25"],
    isSave: false,
    industry: ["ضد لغزش"],
    thickness: "15mm",
  },
  {
    id: 12,
    title: "palette6",
    image: "/images/envairment/12.jpg",
    description: "قالیچه کلاسیک قرمز رنگ مناسب اتاق نشیمن و پذیرایی.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["MONOCOLOR", "ABSTRACT"],
    color: ["قرمز", "نارنجی"],
    size: ["60*60", "33*33"],
    isSave: false,
    industry: ["قطعات تکمیلی"],
    thickness: "11mm",
  },
  {
    id: 13,
    title: "palette7",
    image: "/images/envairment/13.jpg",
    description: "گلدان شیشه‌ای مینیمال مناسب دکوراسیون داخلی.",
    environment: ["استخر-حمام", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["سفید", "آبی"],
    size: ["20*20", "15*15"],
    isSave: true,
    industry: ["ضد قلیا"],
    thickness: "10mm",
  },
  {
    id: 14,
    title: "palette8",
    image: "/images/envairment/14.jpg",
    description: "نیمکت چوبی روستیک مناسب فضای باز و بالکن.",
    environment: ["پارکینگ- محیط خارجی", "نما"],
    style: ["WOOD", "HEAVY DUTY"],
    color: ["قهوه ای", "بژ"],
    size: ["60*60", "40*40"],
    isSave: true,
    industry: ["صنعتی"],
    thickness: "14mm",
  },
  {
    id: 15,
    title: "embossed-elegance",
    image: "/images/envairment/15.jpg",
    description: "صندلی استیل صنعتی مناسب سالن تولید و انبار.",
    environment: ["صنعتی", "نما"],
    style: ["HEAVY DUTY"],
    color: ["خاکستری", "مشکی"],
    size: ["60*60", "40*40"],
    isSave: false,
    industry: ["صنعتی"],
    thickness: "14mm",
  },
  {
    id: 16,
    title: "embossed-elegance",
    image: "/images/envairment/16.jpg",
    description: "چهارپایه مدرن زرد رنگ مناسب آشپزخانه و بالکن.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["زرد", "بژ"],
    size: ["30*30", "25*25"],
    isSave: false,
    industry: ["ضد لغزش"],
    thickness: "15mm",
  },
  {
    id: 17,
    title: "embossed-elegance",
    image: "/images/envairment/17.jpg",
    description: "کابینت آبی کلاسیک مناسب آشپزخانه و دفتر کار.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["MONOCOLOR", "ABSTRACT"],
    color: ["آبی", "سفید"],
    size: ["100*100", "60*60"],
    isSave: false,
    industry: ["قطعات تکمیلی"],
    thickness: "11mm",
  },
  {
    id: 18,
    title: "embossed-elegance",
    image: "/images/envairment/18.jpg",
    description: "چراغ مینیمال مشکی مناسب اتاق خواب و سالن مطالعه.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["مشکی", "خاکستری"],
    size: ["20*20", "25*25"],
    isSave: true,
    industry: ["ضد لغزش"],
    thickness: "11mm",
  },
  {
    id: 19,
    title: "monocolor",
    image: "/images/envairment/19.jpg",
    description: "روکش میز روستیک قرمز مناسب آشپزخانه و سالن تولید.",
    environment: ["صنعتی", "نما"],
    style: ["WOOD", "HEAVY DUTY"],
    color: ["قرمز", "نارنجی"],
    size: ["60*60", "40*40"],
    isSave: false,
    industry: ["صنعتی"],
    thickness: "13mm",
  },
  {
    id: 20,
    title: "monocolor",
    image: "/images/envairment/20.jpg",
    description: "میز خاکستری صنعتی مناسب دفتر کار و انبار.",
    environment: ["صنعتی", "نما"],
    style: ["HEAVY DUTY"],
    color: ["خاکستری", "مشکی"],
    size: ["100*100", "60*60"],
    isSave: false,
    industry: ["صنعتی"],
    thickness: "20mm",
  },
  {
    id: 21,
    title: "monocolor",
    image: "/images/envairment/21.jpg",
    description: "صندلی صورتی مدرن مناسب اتاق خواب و اتاق نشیمن.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["صورتی", "بژ"],
    size: ["40*40", "30*30"],
    isSave: false,
    industry: ["ضد لغزش"],
    thickness: "8mm",
  },
  {
    id: 22,
    title: "monocolor",
    image: "/images/envairment/22.jpg",
    description: "در چوبی کلاسیک مناسب پروژه‌های عمرانی و ساختمان.",
    environment: ["نما"],
    style: ["WOOD", "STONE"],
    color: ["قهوه ای", "بژ"],
    size: ["7*29", "40*40"],
    isSave: true,
    industry: ["قطعات تکمیلی"],
    thickness: "10mm",
  },
  {
    id: 23,
    title: "terrazo",
    image: "/images/envairment/23.jpg",
    description: "صندلی سفید مینیمال مناسب دفتر کار و اتاق خواب.",
    environment: ["صنعتی", "مسکونی"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["سفید", "بژ"],
    size: ["40*40", "25*25"],
    isSave: true,
    industry: ["ضد لغزش"],
    thickness: "8mm",
  },
  {
    id: 24,
    title: "titan",
    image: "/images/envairment/24.jpg",
    description: "کاناپه‌ای مدرن و راحت با رنگ سفید مناسب اتاق نشیمن داخلی.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["سفید", "بژ"],
    size: ["60*60", "40*40"],
    isSave: false,
    industry: [],
    thickness: "20mm",
  },
  {
    id: 25,
    title: "titan2",
    image: "/images/envairment/25.jpg",
    description:
      "چراغی زیبا به سبک روستیک با رنگ طلایی و سایز خیلی بزرگ برای بالکن خارجی.",
    environment: ["پارکینگ- محیط خارجی", "تجاری و پرتردد"],
    style: ["WOOD", "HEAVY DUTY"],
    color: ["زرد", "نارنجی"],
    size: ["100*100", "60*120"],
    isSave: true,
    industry: ["ضد لغزش"],
    thickness: "13mm",
  },
  {
    id: 26,
    title: "barco",
    image: "/images/envairment/26.jpg",
    description:
      "میز کاری مینیمال با رنگ مشکی و اندازه متوسط مناسب فضای دفتر کار.",
    environment: ["تجاری و پرتردد"],
    style: ["WOOD", "MONOCOLOR"],
    color: ["مشکی", "خاکستری"],
    size: ["60*60", "33*33"],
    isSave: false,
    industry: [],
    thickness: "13mm",
  },
  {
    id: 27,
    title: "elegant",
    image: "/images/envairment/27.jpg",
    description: "کابینت آشپزخانه به سبک کلاسیک با رنگ سفید و سایز بزرگ.",
    environment: ["مسکونی"],
    style: ["WOOD", "MARBLE"],
    color: ["سفید"],
    size: ["60*120", "40*40"],
    isSave: false,
    industry: [],
    thickness: "12mm",
  },
  {
    id: 28,
    title: "elegant",
    image: "/images/envairment/28.jpg",
    description:
      "صندلی به رنگ قرمز با طراحی صنعتی، مناسب برای انبار و سالن تولید.",
    environment: ["صنعتی"],
    style: ["HEAVY DUTY"],
    color: ["قرمز", "مشکی"],
    size: ["30*30", "25*25"],
    isSave: true,
    industry: ["صنعتی", "ضد اسید"],
    thickness: "14mm",
  },
  {
    id: 29,
    title: "elegant",
    image: "/images/envairment/29.jpg",
    description: "کرسى مدرن به رنگ آبی مناسب اتاق نشیمن داخلی.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["آبی", "سبز"],
    size: ["20*20", "15*15"],
    isSave: true,
    industry: [],
    thickness: "12mm",
  },
  {
    id: 30,
    title: "gravity",
    image: "/images/envairment/30.jpg",
    description: "پرده‌های کلاسیک به رنگ سبز مناسب اتاق خواب و نشیمن.",
    environment: ["مسکونی"],
    style: ["FABRIC"],
    color: ["سبز", "بژ"],
    size: ["60*60", "40*40"],
    isSave: false,
    industry: [],
    thickness: "8mm",
  },
  {
    id: 31,
    title: "gravity",
    image: "/images/envairment/31.jpg",
    description: "شلف مینیمال سفید رنگ مناسب آشپزخانه و دفتر کار.",
    environment: ["صنعتی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["سفید", "بژ"],
    size: ["60*120", "40*40"],
    isSave: false,
    industry: ["ضد لغزش"],
    thickness: "8mm",
  },
  {
    id: 32,
    title: "limestone",
    image: "/images/envairment/32.jpg",
    description: "میز چوبی روستیک مناسب سالن تولید و فضای باز.",
    environment: ["صنعتی", "نما"],
    style: ["WOOD", "HEAVY DUTY"],
    color: ["قهوه ای", "زرد"],
    size: ["100*100", "60*60"],
    isSave: false,
    industry: ["صنعتی"],
    thickness: "9mm",
  },
  {
    id: 33,
    title: "nepal",
    image: "/images/envairment/33.jpg",
    description: "شلف فلزی صنعتی مناسب انبار و کارخانه.",
    environment: ["صنعتی", "تجاری و پرتردد"],
    style: ["HEAVY DUTY"],
    color: ["خاکستری", "مشکی"],
    size: ["60*60", "33*33"],
    isSave: true,
    industry: ["صنعتی", "ضد اسید"],
    thickness: "9mm",
  },
  {
    id: 34,
    title: "travertan",
    image: "/images/envairment/34.jpg",
    description: "چراغ ایستاده مدرن به رنگ مشکی مناسب سالن پذیرایی.",
    environment: ["دکوراتیو", "مسکونی"],
    style: ["MONOCOLOR", "FABRIC"],
    color: ["مشکی", "سفید"],
    size: ["40*40", "25*25"],
    isSave: false,
    industry: ["ضد لغزش"],
    thickness: "15mm",
  },
  {
    id: 35,
    title: "travertan",
    image: "/images/envairment/35.jpg",
    description: "قالیچه کلاسیک قرمز رنگ مناسب اتاق نشیمن و پذیرایی.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["MONOCOLOR", "ABSTRACT"],
    color: ["قرمز", "نارنجی"],
    size: ["60*60", "33*33"],
    isSave: false,
    industry: ["قطعات تکمیلی"],
    thickness: "11mm",
  },
  {
    id: 36,
    title: "serenity",
    image: "/images/envairment/36.jpg",
    description: "گلدان شیشه‌ای مینیمال مناسب دکوراسیون داخلی.",
    environment: ["استخر-حمام", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["سفید", "آبی"],
    size: ["20*20", "15*15"],
    isSave: true,
    industry: ["ضد قلیا"],
    thickness: "10mm",
  },
  {
    id: 37,
    title: "serenity",
    image: "/images/envairment/37.jpg",
    description: "نیمکت چوبی روستیک مناسب فضای باز و بالکن.",
    environment: ["پارکینگ- محیط خارجی", "نما"],
    style: ["WOOD", "HEAVY DUTY"],
    color: ["قهوه ای", "بژ"],
    size: ["60*60", "40*40"],
    isSave: true,
    industry: ["صنعتی"],
    thickness: "14mm",
  },
  {
    id: 38,
    title: "serenity",
    image: "/images/envairment/38.jpg",
    description: "صندلی استیل صنعتی مناسب سالن تولید و انبار.",
    environment: ["صنعتی", "نما"],
    style: ["HEAVY DUTY"],
    color: ["خاکستری", "مشکی"],
    size: ["60*60", "40*40"],
    isSave: false,
    industry: ["صنعتی"],
    thickness: "14mm",
  },
  {
    id: 39,
    title: "grayscap",
    image: "/images/envairment/39.png",
    description: "چهارپایه مدرن زرد رنگ مناسب آشپزخانه و بالکن.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["FABRIC", "MONOCOLOR"],
    color: ["زرد", "بژ"],
    size: ["30*30", "25*25"],
    isSave: false,
    industry: ["ضد لغزش"],
    thickness: "15mm",
  },
  {
    id: 40,
    title: "onyx",
    image: "/images/envairment/40.jpg",
    description: "کابینت آبی کلاسیک مناسب آشپزخانه و دفتر کار.",
    environment: ["مسکونی", "دکوراتیو"],
    style: ["MONOCOLOR", "ABSTRACT"],
    color: ["آبی", "سفید"],
    size: ["100*100", "60*60"],
    isSave: false,
    industry: ["قطعات تکمیلی"],
    thickness: "11mm",
  },
];

// export const products = [
//   {
//     id: 1,
//     title: "سرامیک 1",
//     image: "/images/12.png",
//     description: "کاناپه‌ای مدرن و راحت با رنگ سفید مناسب اتاق نشیمن داخلی.",
//     environment: ["مسکونی", "دکوراتیو"],
//     style: ["FABRIC", "MONOCOLOR"],
//     color: ["سفید", "بژ"],
//     size: ["60*60", "40*40"],
//     isSave: false,
//     industry: [],
//     thickness: "20mm",
//   },
//   {
//     id: 2,
//     title: "سرامیک 2",
//     image: "/images/18.png",
//     description:
//       "چراغی زیبا به سبک روستیک با رنگ طلایی و سایز خیلی بزرگ برای بالکن خارجی.",
//     environment: ["پارکینگ- محیط خارجی", "تجاری و پرتردد"],
//     style: ["WOOD", "HEAVY DUTY"],
//     color: ["زرد", "نارنجی"],
//     size: ["100*100", "60*120"],
//     isSave: true,
//     industry: ["ضد لغزش"],
//     thickness: "13mm",
//   },
//   {
//     id: 3,
//     title: "سرامیک 3",
//     image: "/images/1.png",
//     description:
//       "میز کاری مینیمال با رنگ مشکی و اندازه متوسط مناسب فضای دفتر کار.",
//     environment: ["تجاری و پرتردد"],
//     style: ["WOOD", "MONOCOLOR"],
//     color: ["مشکی", "خاکستری"],
//     size: ["60*60", "33*33"],
//     isSave: false,
//     industry: [],
//     thickness: "13mm",
//   },
//   {
//     id: 4,
//     title: "سرامیک 4",
//     image: "/images/14.png",
//     description: "کابینت آشپزخانه به سبک کلاسیک با رنگ سفید و سایز بزرگ.",
//     environment: ["مسکونی"],
//     style: ["WOOD", "MARBLE"],
//     color: ["سفید"],
//     size: ["60*120", "40*40"],
//     isSave: false,
//     industry: [],
//     thickness: "12mm",
//   },
//   {
//     id: 5,
//     title: "سرامیک 5",
//     image: "/images/3.png",
//     description:
//       "صندلی به رنگ قرمز با طراحی صنعتی، مناسب برای انبار و سالن تولید.",
//     environment: ["صنعتی"],
//     style: ["HEAVY DUTY"],
//     color: ["قرمز", "مشکی"],
//     size: ["30*30", "25*25"],
//     isSave: true,
//     industry: ["صنعتی", "ضد اسید"],
//     thickness: "14mm",
//   },
//   {
//     id: 6,
//     title: "سرامیک 6",
//     image: "/images/17.png",
//     description: "کرسى مدرن به رنگ آبی مناسب اتاق نشیمن داخلی.",
//     environment: ["مسکونی", "دکوراتیو"],
//     style: ["FABRIC", "MONOCOLOR"],
//     color: ["آبی", "سبز"],
//     size: ["20*20", "15*15"],
//     isSave: true,
//     industry: [],
//     thickness: "12mm",
//   },
//   {
//     id: 7,
//     title: "سرامیک 7",
//     image: "/images/16.png",
//     description: "پرده‌های کلاسیک به رنگ سبز مناسب اتاق خواب و نشیمن.",
//     environment: ["مسکونی"],
//     style: ["FABRIC"],
//     color: ["سبز", "بژ"],
//     size: ["60*60", "40*40"],
//     isSave: false,
//     industry: [],
//     thickness: "8mm",
//   },
//   {
//     id: 8,
//     title: "سرامیک 8",
//     image: "/images/13.png",
//     description: "شلف مینیمال سفید رنگ مناسب آشپزخانه و دفتر کار.",
//     environment: ["صنعتی", "دکوراتیو"],
//     style: ["FABRIC", "MONOCOLOR"],
//     color: ["سفید", "بژ"],
//     size: ["60*120", "40*40"],
//     isSave: false,
//     industry: ["ضد لغزش"],
//     thickness: "8mm",
//   },
//   {
//     id: 9,
//     title: "سرامیک 9",
//     image: "/images/44.png",
//     description: "میز چوبی روستیک مناسب سالن تولید و فضای باز.",
//     environment: ["صنعتی", "نما"],
//     style: ["WOOD", "HEAVY DUTY"],
//     color: ["قهوه ای", "زرد"],
//     size: ["100*100", "60*60"],
//     isSave: false,
//     industry: ["صنعتی"],
//     thickness: "9mm",
//   },
//   {
//     id: 10,
//     title: "سرامیک 10",
//     image: "/images/1.png",
//     description: "شلف فلزی صنعتی مناسب انبار و کارخانه.",
//     environment: ["صنعتی", "تجاری و پرتردد"],
//     style: ["HEAVY DUTY"],
//     color: ["خاکستری", "مشکی"],
//     size: ["60*60", "33*33"],
//     isSave: true,
//     industry: ["صنعتی", "ضد اسید"],
//     thickness: "9mm",
//   },
//   {
//     id: 11,
//     title: "سرامیک 11",
//     image: "/images/1.png",
//     description: "چراغ ایستاده مدرن به رنگ مشکی مناسب سالن پذیرایی.",
//     environment: ["دکوراتیو", "مسکونی"],
//     style: ["MONOCOLOR", "FABRIC"],
//     color: ["مشکی", "سفید"],
//     size: ["40*40", "25*25"],
//     isSave: false,
//     industry: ["ضد لغزش"],
//     thickness: "15mm",
//   },
//   {
//     id: 12,
//     title: "سرامیک 12",
//     image: "/images/1.png",
//     description: "قالیچه کلاسیک قرمز رنگ مناسب اتاق نشیمن و پذیرایی.",
//     environment: ["مسکونی", "دکوراتیو"],
//     style: ["MONOCOLOR", "ABSTRACT"],
//     color: ["قرمز", "نارنجی"],
//     size: ["60*60", "33*33"],
//     isSave: false,
//     industry: ["قطعات تکمیلی"],
//     thickness: "11mm",
//   },
//   {
//     id: 13,
//     title: "سرامیک 13",
//     image: "/images/1.png",
//     description: "گلدان شیشه‌ای مینیمال مناسب دکوراسیون داخلی.",
//     environment: ["استخر-حمام", "دکوراتیو"],
//     style: ["FABRIC", "MONOCOLOR"],
//     color: ["سفید", "آبی"],
//     size: ["20*20", "15*15"],
//     isSave: true,
//     industry: ["ضد قلیا"],
//     thickness: "10mm",
//   },
//   {
//     id: 14,
//     title: "سرامیک 14",
//     image: "/images/1.png",
//     description: "نیمکت چوبی روستیک مناسب فضای باز و بالکن.",
//     environment: ["پارکینگ- محیط خارجی", "نما"],
//     style: ["WOOD", "HEAVY DUTY"],
//     color: ["قهوه ای", "بژ"],
//     size: ["60*60", "40*40"],
//     isSave: true,
//     industry: ["صنعتی"],
//     thickness: "14mm",
//   },
//   {
//     id: 15,
//     title: "سرامیک 15",
//     image: "/images/1.png",
//     description: "صندلی استیل صنعتی مناسب سالن تولید و انبار.",
//     environment: ["صنعتی", "نما"],
//     style: ["HEAVY DUTY"],
//     color: ["خاکستری", "مشکی"],
//     size: ["60*60", "40*40"],
//     isSave: false,
//     industry: ["صنعتی"],
//     thickness: "14mm",
//   },
//   {
//     id: 16,
//     title: "سرامیک 16",
//     image: "/images/1.png",
//     description: "چهارپایه مدرن زرد رنگ مناسب آشپزخانه و بالکن.",
//     environment: ["مسکونی", "دکوراتیو"],
//     style: ["FABRIC", "MONOCOLOR"],
//     color: ["زرد", "بژ"],
//     size: ["30*30", "25*25"],
//     isSave: false,
//     industry: ["ضد لغزش"],
//     thickness: "15mm",
//   },
//   {
//     id: 17,
//     title: "سرامیک 17",
//     image: "/images/1.png",
//     description: "کابینت آبی کلاسیک مناسب آشپزخانه و دفتر کار.",
//     environment: ["مسکونی", "دکوراتیو"],
//     style: ["MONOCOLOR", "ABSTRACT"],
//     color: ["آبی", "سفید"],
//     size: ["100*100", "60*60"],
//     isSave: false,
//     industry: ["قطعات تکمیلی"],
//     thickness: "11mm",
//   },
//   {
//     id: 18,
//     title: "سرامیک 18",
//     image: "/images/1.png",
//     description: "چراغ مینیمال مشکی مناسب اتاق خواب و سالن مطالعه.",
//     environment: ["مسکونی", "دکوراتیو"],
//     style: ["FABRIC", "MONOCOLOR"],
//     color: ["مشکی", "خاکستری"],
//     size: ["20*20", "25*25"],
//     isSave: true,
//     industry: ["ضد لغزش"],
//     thickness: "11mm",
//   },
//   {
//     id: 19,
//     title: "سرامیک 19",
//     image: "/images/1.png",
//     description: "روکش میز روستیک قرمز مناسب آشپزخانه و سالن تولید.",
//     environment: ["صنعتی", "نما"],
//     style: ["WOOD", "HEAVY DUTY"],
//     color: ["قرمز", "نارنجی"],
//     size: ["60*60", "40*40"],
//     isSave: false,
//     industry: ["صنعتی"],
//     thickness: "13mm",
//   },
//   {
//     id: 20,
//     title: "سرامیک 20",
//     image: "/images/1.png",
//     description: "میز خاکستری صنعتی مناسب دفتر کار و انبار.",
//     environment: ["صنعتی", "نما"],
//     style: ["HEAVY DUTY"],
//     color: ["خاکستری", "مشکی"],
//     size: ["100*100", "60*60"],
//     isSave: false,
//     industry: ["صنعتی"],
//     thickness: "20mm",
//   },
//   {
//     id: 21,
//     title: "سرامیک 21",
//     image: "/images/1.png",
//     description: "صندلی صورتی مدرن مناسب اتاق خواب و اتاق نشیمن.",
//     environment: ["مسکونی", "دکوراتیو"],
//     style: ["FABRIC", "MONOCOLOR"],
//     color: ["صورتی", "بژ"],
//     size: ["40*40", "30*30"],
//     isSave: false,
//     industry: ["ضد لغزش"],
//     thickness: "8mm",
//   },
//   {
//     id: 22,
//     title: "سرامیک 22",
//     image: "/images/1.png",
//     description: "در چوبی کلاسیک مناسب پروژه‌های عمرانی و ساختمان.",
//     environment: ["نما"],
//     style: ["WOOD", "STONE"],
//     color: ["قهوه ای", "بژ"],
//     size: ["7*29", "40*40"],
//     isSave: true,
//     industry: ["قطعات تکمیلی"],
//     thickness: "10mm",
//   },
//   {
//     id: 23,
//     title: "سرامیک 23",
//     image: "/images/1.png",
//     description: "صندلی سفید مینیمال مناسب دفتر کار و اتاق خواب.",
//     environment: ["صنعتی", "مسکونی"],
//     style: ["FABRIC", "MONOCOLOR"],
//     color: ["سفید", "بژ"],
//     size: ["40*40", "25*25"],
//     isSave: true,
//     industry: ["ضد لغزش"],
//     thickness: "8mm",
//   },
// ];
